# Generated by Django 3.1.1 on 2020-11-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('MOQ', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('category', models.CharField(choices=[('AN', 'animal feeds'), ('FZ', 'fertilizers'), ('SD', 'seeds'), ('AC', 'farm accesories')], max_length=2)),
            ],
        ),
    ]
